name: mira_care
description: Health Care app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  intervalprogressbar: ^2.0.1
  google_fonts: ^4.0.3
  file_picker: ^5.2.7
  video_thumbnail: ^0.5.3
  http: ^0.13.5
  simple_gesture_detector: ^0.2.0
  day_night_time_picker: ^1.2.0+2
  dropdown_button2: ^2.0.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  mime: ^1.0.4
  uuid: ^3.0.7
  flutter_holo_date_picker: ^1.1.0
  url_launcher: ^6.1.10
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  ably_flutter: ^1.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/mira_background.png
    - assets/images/logo.png
    # Icon images
    - assets/images/dash.png
    - assets/images/calendar.png
    - assets/images/community.png
    - assets/images/contact.png
    - assets/images/journal.png
    - assets/images/message.png
    - assets/images/profile.png
    - assets/images/reporting.png
    - assets/images/settings.png
    - assets/images/analytics.png
    # Card Images
    - assets/images/blood_pressure.png
    - assets/images/heart_rate.png
    - assets/images/sleep_rate.png
    - assets/images/oxy_level.png
    - assets/images/breath_rate.png
    - assets/images/temp.png
    - assets/images/glucose.png
    - assets/images/weight.png
    # Sleep Card Images
    - assets/images/score.png
    # Journal Note Images
    - assets/images/pin_icon.png
    - assets/images/document_preview.png
    - assets/images/music_preview.png
    - assets/images/pdf_preview.png
    - assets/images/img_preview.png
    # Calendar Images
    - assets/images/calendar_img.png
    - assets/images/search_img.png
    # Community Images
    - assets/images/img_msg.png
    - assets/images/img_phone.png
    - assets/images/img_error_contact.png
